### ISSUE TITLE
Don't evaluate `@reached_if` unless the goal is required

### ISSUE THREAD

**Issue by 08d2** [xonixx/makesure#104]
Thanks for the brilliant tool.

I have a Makesurefile with goals that are intended to be executed in different environments. Concretely, there is a `@goal build` which I can run on my macOS laptop, and a `@goal install` which only makes sense to run on my Debian server. The install goal has some transitive goals with `@reached_if` directives that invoke `systemctl`. When I `makesure build` on my laptop, I get some errors about systemctl not being installed. It seems that all `@reached_if` directives in a Makesurefile are evaluated greedily, even if the requested goal wouldn't ever reach them. I guess that would ideally not be the case :)

**Comment by xonixx** [comment]
Thank you for your kind words and the proposal.

Your guess of greedy `@reached_if` evaluation is correct. The reason for this is that this information is used for topological sort routine needed to determine the correct execution order of goals. 

However I totally agree that from a user perspective your request is completely valid and rational. I’ll check with implementation and will be glad if I can find a way to make it work this way without breaking things. Not only this is more logical but also should be more efficient.
