### ISSUE TITLE
Gawk warns about obsolete time extension

### ISSUE THREAD

**Issue by AdamantGarth** [xonixx/makesure#118]
OS: Arch Linux
```
$ ./makesure --version
gawk: warning: The time extension is obsolete. Use the timex extension from gawkextlib instead.
0.9.19
```
```
$ gawk --version | head -n1
GNU Awk 5.2.1, API 3.2, PMA Avon 8-g1, (GNU MPFR 4.1.1-p1, GNU MP 6.2.1)
```

**Comment by xonixx** [comment]
Thank you for the report! Let's see what can be done here.

**Comment by xonixx** [comment]
Asked in Gawk mailing list if it would be possible to keep the `getttimeofday()` function we rely on: https://lists.gnu.org/archive/html/bug-gawk/2023-01/msg00017.html. 

If not, we'll drop the usage of it. This means on macOS the timings precision will be back to 1 sec (#51) unless we find another way.

**Comment by xonixx** [comment]
Hey @AdamantGarth. So Gawk creators agree to un-deprecate the time extension, so I hope the warning will go away with next Gawk version. 

Let me know if the issue is critical to you now and we'll think what can we do meanwhile.

**Comment by AdamantGarth** [comment]
Oh, that's great! I downgraded my Gawk for the time being, so it's not a problem at all. I'll close the issue now, cause there's nothing left to do on `makesure`'s side, and I might forget to close it after Gawk updates :)
