### ISSUE TITLE
regex issue at minify.awk

### ISSUE THREAD

**Issue by mogando668** [xonixx/makesure#137]
`  gsub(/) {/, "){")
`

This one is an error on some `awk`s. Safest way is to always use square brackets regardless whether it's for opening or closing , e.g.

`  gsub(/[)] [{]/, "){")
`

in fact, every `ASCII `punctuation symbol could be cleanly escaped via `[…]`, with 2 special case considerations - the caret  anchor` ^ ` ( only if it's first or only object ) and backslash` \` still needs to be backslash-escaped, even inside square brackets :

```
/[\^]/   ( if first or only )
/[][^]+/ ( if mixed with others )

/[\\]/

```

**Comment by xonixx** [comment]
Thank you. Indeed mawk 1.3.3, busybox awk and GoAWK fail on this.

**Comment by xonixx** [comment]
Fixed.
