### ISSUE TITLE
Installation not working on Windows (via Git Bash)

### ISSUE THREAD

**Issue by LevT2** [xonixx/makesure#94]
as there is no `wget` inside the Git Bash.
The powershell alias to `iwr (Invoke-WebRequest)` is a totally different and incompatible beast.

**Comment by xonixx** [comment]
Thank you for your report! 
I bet Git Bash should have curl bundled - could you please check? I believe at least latest Git Win distribution should include.

**Comment by xonixx** [comment]
Hey @LevT2 I've adjusted the Installation section https://github.com/xonixx/makesure#installation.
Now command with curl should work in Git Bash.
